name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0  
  lottie: ^3.1.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  flutter_bloc: ^8.1.5
  geocoding: ^3.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
